.TH GENROMFS 8 "Aug 1997" "Version 0.2"
.SH NAME
genromfs \- create a romfs image
.SH SYNOPSIS
.B genromfs
.B \-f device
[
.B \-d source
]
[
.B \-V volumename
]
[
.B \-v
]
.SH DESCRIPTION
.B genromfs
is used to create a romfs file system image, usually directly on
a block device, or for test purposes, in a plain file.
It is the
.I mkfs
equivalent of other filesystems.
.PP
.B genromfs
will scan the current directory and its subdirectories, build a romfs
image from the files found, and output it to the file or device you
specified.
.SH OPTIONS
.TP
.BI -f \ output
Specifies the file to output the image to.  It must be specified.
.TP
.BI -d \ source
Use the specified directory as the source, not the current directory.
.TP
.BI -V \ volumename
Build the image with the specified volume name.  Currently it is
not used by the kernel, but might be useful for some purposes.
.TP
.BI -v
Verbose operation,
.B genromfs
will print every file which are included in the image, along with
its offset.
.SH EXAMPLES
.PP
.B genromfs -d root -f /dev/fd0 -V 'Secret labs install disk'
.PP
All files in the 
.I root
directory will be written to 
.B /dev/fd0
as a new romfs filesystem image.  You can mount it (if you have the
romfs module loaded, or compiled into the kernel) via:
.PP
.B mount -t romfs /dev/fd0 /mnt
.PP
.SH AUTHOR
This manual page was initially written by Christoph Lameter <clameter@debian.org>,
for the Debian GNU/Linux system.
.SH SEE ALSO
.BR mkfs (8),
.BR mount (8),
.BR mkisofs (8)
